"""
Compare part-of-speech tagging output from NLTK and TextBlob.

This script lets a user choose an NLTK corpus and text file, then compares
the POS-tagged output generated by NLTK and TextBlob.
"""

from collections import Counter
import nltk
from nltk.corpus import brown, gutenberg, inaugural, reuters, webtext
from textblob import TextBlob


CORPORA = {
    "brown": brown,
    "gutenberg": gutenberg,
    "inaugural": inaugural,
    "reuters": reuters,
    "webtext": webtext,
}


def choose_corpus():
    """Prompt the user to choose an available NLTK corpus."""
    print("Available corpora:")
    for name in CORPORA:
        print(f"- {name}")

    while True:
        choice = input("\nChoose a corpus: ").strip().lower()
        if choice in CORPORA:
            return choice, CORPORA[choice]

        print("Invalid corpus. Please choose one from the list.")


def choose_file(corpus):
    """Prompt the user to choose a file from the selected corpus."""
    file_ids = corpus.fileids()

    print("\nAvailable files:")
    for file_id in file_ids[:25]:
        print(f"- {file_id}")

    if len(file_ids) > 25:
        print(f"...and {len(file_ids) - 25} more")

    while True:
        choice = input("\nChoose a file ID: ").strip()
        if choice in file_ids:
            return choice

        print("Invalid file ID. Please copy one exactly from the corpus list.")


def get_text(corpus, file_id):
    """Return raw text from a selected corpus file."""
    return corpus.raw(file_id)


def tag_with_nltk(text):
    """Tokenize and tag text using NLTK."""
    tokens = nltk.word_tokenize(text)
    return nltk.pos_tag(tokens)


def tag_with_textblob(text):
    """Tag text using TextBlob."""
    blob = TextBlob(text)
    return list(blob.tags)


def compare_taggers(nltk_tags, textblob_tags):
    """Compare POS tag outputs from NLTK and TextBlob."""
    nltk_count = len(nltk_tags)
    textblob_count = len(textblob_tags)

    print("\nTagger Output Summary")
    print("---------------------")
    print(f"NLTK token/tag count: {nltk_count}")
    print(f"TextBlob token/tag count: {textblob_count}")

    if nltk_count != textblob_count:
        print("\nThe taggers produced different token counts.")
        print("This usually means they tokenized the text differently.")
        return

    differences = []

    for index, (nltk_pair, textblob_pair) in enumerate(zip(nltk_tags, textblob_tags)):
        nltk_word, nltk_tag = nltk_pair
        textblob_word, textblob_tag = textblob_pair

        if nltk_word != textblob_word or nltk_tag != textblob_tag:
            differences.append(
                {
                    "index": index,
                    "nltk": nltk_pair,
                    "textblob": textblob_pair,
                }
            )

    print(f"\nNumber of differing tags/tokens: {len(differences)}")

    if differences:
        print("\nFirst 20 differences:")
        for item in differences[:20]:
            print(
                f"{item['index']}: "
                f"NLTK={item['nltk']} | TextBlob={item['textblob']}"
            )


def summarize_tags(tags, label):
    """Print the most common POS tags from a tagger output."""
    tag_counts = Counter(tag for _, tag in tags)

    print(f"\nMost common {label} POS tags:")
    print("-----------------------------")
    for tag, count in tag_counts.most_common(10):
        print(f"{tag}: {count}")


def main():
    """Run the POS comparison workflow."""
    corpus_name, corpus = choose_corpus()
    file_id = choose_file(corpus)
    text = get_text(corpus, file_id)

    print(f"\nAnalyzing {file_id} from the {corpus_name} corpus...")

    nltk_tags = tag_with_nltk(text)
    textblob_tags = tag_with_textblob(text)

    compare_taggers(nltk_tags, textblob_tags)
    summarize_tags(nltk_tags, "NLTK")
    summarize_tags(textblob_tags, "TextBlob")


if __name__ == "__main__":
    main()
